import type { AppStore } from '../types.ts'

const now = new Date().toISOString()

export const seedStore: AppStore = {
  users: [
    {
      id: 'usr_admin',
      name: 'Administrador Escudo Noventa',
      email: 'admin@escudonoventa.com',
      password: 'admin123',
      role: 'admin',
      phone: '(11) 90000-0000',
      favorites: ['brasil-1970-retro', 'milan-champions'],
      createdAt: now,
      addresses: [
        {
          id: 'addr_admin',
          label: 'Escritório',
          zipCode: '01001-000',
          street: 'Praça da Sé',
          number: '100',
          district: 'Sé',
          city: 'São Paulo',
          state: 'SP',
        },
      ],
    },
    {
      id: 'usr_customer',
      name: 'Marcos Oliveira',
      email: 'cliente@escudonoventa.com',
      password: 'cliente123',
      role: 'customer',
      phone: '(21) 98888-7777',
      favorites: ['boca-juniors-home'],
      createdAt: now,
      addresses: [
        {
          id: 'addr_customer',
          label: 'Casa',
          zipCode: '22041-001',
          street: 'Avenida Atlântica',
          number: '500',
          district: 'Copacabana',
          city: 'Rio de Janeiro',
          state: 'RJ',
        },
      ],
    },
  ],
  categories: [
    {
      id: 'cat_brasileirao',
      name: 'Brasileirão',
      slug: 'brasileirao',
      description: 'Clubes nacionais, clássicos e lançamentos.',
      active: true,
    },
    {
      id: 'cat_premier',
      name: 'Premier League',
      slug: 'premier-league',
      description: 'Camisas oficiais e especiais do futebol inglês.',
      active: true,
    },
    {
      id: 'cat_laliga',
      name: 'La Liga',
      slug: 'la-liga',
      description: 'Gigantes espanhóis com acabamento premium.',
      active: true,
    },
    {
      id: 'cat_champions',
      name: 'Champions League',
      slug: 'champions-league',
      description: 'Edições europeias para noites históricas.',
      active: true,
    },
    {
      id: 'cat_selecoes',
      name: 'Seleções',
      slug: 'selecoes',
      description: 'Brasil, Argentina, Itália, França e outras seleções.',
      active: true,
    },
    {
      id: 'cat_retro',
      name: 'Retrô',
      slug: 'retro',
      description: 'Camisas clássicas para colecionadores.',
      active: true,
    },
  ],
  products: [
    {
      id: 'brasil-1970-retro',
      name: 'Brasil Retrô 1970',
      club: 'Seleção Brasileira',
      season: 'Retrô 1970',
      categoryId: 'cat_selecoes',
      league: 'Copa do Mundo',
      country: 'Brasil',
      description: 'Camisa amarela clássica com gola retrô, tecido premium e escudo bordado.',
      price: 289.9,
      oldPrice: 349.9,
      rating: 4.9,
      reviewsCount: 328,
      stock: 18,
      badge: 'Coleção ouro',
      colors: ['#FFD700', '#0047A1'],
      sizes: ['P', 'M', 'G', 'GG', 'XG'],
      images: ['/products/brasil-1970-retro.png'],
      active: true,
      createdAt: now,
    },
    {
      id: 'chelsea-home-2026',
      name: 'Chelsea Home 2026',
      club: 'Chelsea',
      season: '2026 Home',
      categoryId: 'cat_premier',
      league: 'Premier League',
      country: 'Inglaterra',
      description: 'Modelo azul intenso com respirabilidade alta e detalhes dourados discretos.',
      price: 349.9,
      rating: 4.8,
      reviewsCount: 214,
      stock: 27,
      badge: 'Lançamento',
      colors: ['#0047A1', '#FFD700'],
      sizes: ['P', 'M', 'G', 'GG'],
      images: ['/products/chelsea-home-2026.png'],
      active: true,
      createdAt: now,
    },
    {
      id: 'boca-juniors-home',
      name: 'Boca Juniors Home',
      club: 'Boca Juniors',
      season: '2026 Home',
      categoryId: 'cat_champions',
      league: 'Libertadores',
      country: 'Argentina',
      description: 'Azul e ouro em uma das camisas mais reconhecidas do futebol sul-americano.',
      price: 319.9,
      oldPrice: 379.9,
      rating: 4.7,
      reviewsCount: 176,
      stock: 11,
      badge: 'Mais vendida',
      colors: ['#001A3D', '#FFD700'],
      sizes: ['M', 'G', 'GG', 'XG'],
      images: ['/products/boca-juniors-home.png'],
      active: true,
      createdAt: now,
    },
    {
      id: 'real-madrid-away',
      name: 'Real Madrid Away',
      club: 'Real Madrid',
      season: '2026 Away',
      categoryId: 'cat_laliga',
      league: 'La Liga',
      country: 'Espanha',
      description: 'Camisa clara com visual limpo, escudo em relevo e composição premium.',
      price: 359.9,
      rating: 4.9,
      reviewsCount: 251,
      stock: 22,
      badge: 'Premium',
      colors: ['#F5F5F5', '#0047A1'],
      sizes: ['P', 'M', 'G', 'GG', 'XG'],
      images: ['/products/real-madrid-away.png'],
      active: true,
      createdAt: now,
    },
    {
      id: 'milan-champions',
      name: 'Milan Champions Night',
      club: 'AC Milan',
      season: '2026 Especial',
      categoryId: 'cat_champions',
      league: 'Champions League',
      country: 'Itália',
      description: 'Edição especial para noites europeias, com listras marcantes e selo de colecionador.',
      price: 399.9,
      oldPrice: 449.9,
      rating: 4.9,
      reviewsCount: 143,
      stock: 8,
      badge: 'Limitada',
      colors: ['#333333', '#C62828'],
      sizes: ['M', 'G', 'GG'],
      images: ['/products/milan-champions.png'],
      active: true,
      createdAt: now,
    },
  ],
  coupons: [
    {
      id: 'cpn_torcida10',
      code: 'TORCIDA10',
      description: '10% de desconto em camisas selecionadas.',
      percent: 10,
      active: true,
      expiresAt: '2026-12-31T23:59:59.000Z',
    },
    {
      id: 'cpn_retro15',
      code: 'RETRO15',
      description: '15% de desconto em camisas retrô.',
      percent: 15,
      active: true,
      expiresAt: '2026-12-31T23:59:59.000Z',
    },
  ],
  reviews: [
    {
      id: 'rev_1',
      productId: 'brasil-1970-retro',
      userId: 'usr_customer',
      rating: 5,
      comment: 'Qualidade excelente, tecido confortável e acabamento premium.',
      createdAt: now,
    },
  ],
  cartItems: [],
  orders: [],
  payments: [],
}
