import type { CategoryCard, Product } from '../types/product'
import brasilImage from '../assets/jersey-brasil.jpg'
import redImage from '../assets/jersey-red.jpg'
import blaugranaImage from '../assets/jersey-blaugrana.jpg'
import whiteImage from '../assets/jersey-white.jpg'
import skyblueImage from '../assets/jersey-skyblue.jpg'
import stripesImage from '../assets/jersey-stripes.jpg'

export const categories: CategoryCard[] = [
  {
    id: 'brasileirao',
    name: 'Brasileirão',
    description: 'Clubes nacionais, clássicos e lançamentos.',
    count: 48,
    color: '#0047A1',
  },
  {
    id: 'premier-league',
    name: 'Premier League',
    description: 'Camisas oficiais e edicoes especiais inglesas.',
    count: 36,
    color: '#00A6D6',
  },
  {
    id: 'la-liga',
    name: 'La Liga',
    description: 'Gigantes espanhóis com acabamento premium.',
    count: 29,
    color: '#FFD700',
  },
  {
    id: 'champions',
    name: 'Champions League',
    description: 'Mantôs europeus para noites historicas.',
    count: 32,
    color: '#001A3D',
  },
  {
    id: 'selecoes',
    name: 'Seleções',
    description: 'Brasil, Argentina, Italia, Franca e mais.',
    count: 42,
    color: '#F5F5F5',
  },
]

export const products: Product[] = [
  {
    id: 'brasil-1970-retro',
    name: 'Brasil Retrô 1970',
    club: 'Selecao Brasileira',
    season: 'Retrô 1970',
    category: 'Seleções',
    league: 'Copa do Mundo',
    country: 'Brasil',
    description:
      'Camisa amarela clássica inspirada no futebol arte, com tecido macio, gola retrô e escudo bordado.',
    price: 289.9,
    oldPrice: 349.9,
    rating: 4.9,
    reviews: 328,
    stock: 18,
    badge: 'Colecao ouro',
    colors: ['#FFD700', '#0047A1'],
    sizes: ['P', 'M', 'G', 'GG', 'XG'],
    image: brasilImage,
  },
  {
    id: 'chelsea-home-2026',
    name: 'Chelsea Home 2026',
    club: 'Chelsea',
    season: '2026 Home',
    category: 'Clubes',
    league: 'Premier League',
    country: 'Inglaterra',
    description:
      'Modelo azul intenso com acabamento esportivo, respirabilidade alta e detalhes dourados discretos.',
    price: 349.9,
    rating: 4.8,
    reviews: 214,
    stock: 27,
    badge: 'Lancamento',
    colors: ['#0047A1', '#FFD700'],
    sizes: ['P', 'M', 'G', 'GG'],
    image: skyblueImage,
  },
  {
    id: 'boca-juniors-home',
    name: 'Boca Juniors Home',
    club: 'Boca Juniors',
    season: '2026 Home',
    category: 'Clubes',
    league: 'Libertadores',
    country: 'Argentina',
    description:
      'Azul e ouro em uma das camisas mais reconhecidas do futebol sul-americano, com caimento regular.',
    price: 319.9,
    oldPrice: 379.9,
    rating: 4.7,
    reviews: 176,
    stock: 11,
    badge: 'Mais vendida',
    colors: ['#001A3D', '#FFD700'],
    sizes: ['M', 'G', 'GG', 'XG'],
    image: redImage,
  },
  {
    id: 'real-madrid-away',
    name: 'Real Madrid Away',
    club: 'Real Madrid',
    season: '2026 Away',
    category: 'Clubes',
    league: 'La Liga',
    country: 'Espanha',
    description:
      'Camisa clara com visual limpo, escudo em relevo e composicao premium para uso casual ou colecao.',
    price: 359.9,
    rating: 4.9,
    reviews: 251,
    stock: 22,
    badge: 'Premium',
    colors: ['#F5F5F5', '#0047A1'],
    sizes: ['P', 'M', 'G', 'GG', 'XG'],
    image: whiteImage,
  },
  {
    id: 'manchester-city-third',
    name: 'Manchester City Third',
    club: 'Manchester City',
    season: '2026 Third',
    category: 'Clubes',
    league: 'Premier League',
    country: 'Inglaterra',
    description:
      'Azul claro com contrastes modernos, tecido leve e modelagem atletica para alta performance.',
    price: 339.9,
    rating: 4.8,
    reviews: 198,
    stock: 15,
    badge: 'Top avaliada',
    colors: ['#42A5F5', '#001A3D'],
    sizes: ['P', 'M', 'G', 'GG'],
    image: skyblueImage,
  },
  {
    id: 'milan-champions',
    name: 'Milan Champions Night',
    club: 'AC Milan',
    season: '2026 Especial',
    category: 'Especiais',
    league: 'Champions League',
    country: 'Italia',
    description:
      'Edicao especial para noites europeias, com listras marcantes, tecido premium e selo de colecionador.',
    price: 399.9,
    oldPrice: 449.9,
    rating: 4.9,
    reviews: 143,
    stock: 8,
    badge: 'Limitada',
    colors: ['#333333', '#C62828'],
    sizes: ['M', 'G', 'GG'],
    image: stripesImage,
  },
  {
    id: 'psg-special-gold',
    name: 'PSG Special Gold',
    club: 'Paris Saint-Germain',
    season: '2026 Especial',
    category: 'Especiais',
    league: 'Ligue 1',
    country: 'Franca',
    description:
      'Azul escuro com detalhes em amarelo ouro, visual urbano e acabamento sofisticado.',
    price: 389.9,
    rating: 4.7,
    reviews: 122,
    stock: 13,
    badge: 'Exclusiva',
    colors: ['#001A3D', '#FFD700'],
    sizes: ['P', 'M', 'G', 'GG', 'XG'],
    image: blaugranaImage,
  },
  {
    id: 'corinthians-retro-1990',
    name: 'Corinthians Retrô 1990',
    club: 'Corinthians',
    season: 'Retrô 1990',
    category: 'Retrô',
    league: 'Brasileirão',
    country: 'Brasil',
    description:
      'Camisa branca retrô com gola clássica, tecido confortável e identidade histórica do futebol nacional.',
    price: 279.9,
    rating: 4.8,
    reviews: 189,
    stock: 19,
    badge: 'Retrô',
    colors: ['#FFFFFF', '#333333'],
    sizes: ['P', 'M', 'G', 'GG'],
    image: stripesImage,
  },
]

export const featuredProducts = products.slice(0, 6)

export const cartPreview = [
  { product: products[0], size: 'M', quantity: 1 },
  { product: products[2], size: 'G', quantity: 1 },
  { product: products[4], size: 'M', quantity: 1 },
]
